# Generated by Django 4.0.2 on 2022-02-20 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 9, 33, 58, 736649, tzinfo=utc)),
        ),
    ]
